version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: pip install -r requirements-test.txt
      - run: coverage run -m unittest discover
      - run: coveralls
